#!/bin/bash

# Help script for Backthynk Development Makefile
source "$(dirname "$0")/../common/load-config.sh"

echo -e "${BOLD}${CYAN}Backthynk Development Makefile${NC}"
echo -e "${CYAN}==============================${NC}"
echo ""
echo -e "${BOLD}Available targets:${NC}"
echo ""
echo -e "  ${YELLOW}Build & Run:${NC}"
echo -e "    ${GREEN}build${NC}                    Build production-optimized binary with compressed assets"
echo -e "    ${GREEN}dev${NC}                      Run server in development mode (go run, no build)"
echo -e "    ${GREEN}dev-prod${NC}                 Run server with production assets (go run + production env)"
echo -e "    ${GREEN}run${NC}                      Alias for 'dev'"
echo ""
echo -e "  ${YELLOW}Clean:${NC}"
echo -e "    ${GREEN}clean${NC}                    Clean build artifacts"
echo -e "    ${GREEN}fclean${NC}                   Deep clean (build, cache, node_modules)"
echo ""
echo -e "  ${YELLOW}Testing:${NC}"
echo -e "    ${GREEN}test${NC}                     Run all backend unit tests"
echo -e "    ${GREEN}test-verbose${NC}             Run all backend unit tests with verbose output"
echo ""
echo -e "${GRAY}For development tools (generate posts, list categories), see:${NC}"
echo -e "${GRAY}  cd scripts/dev && make help${NC}"
echo ""
