#!/bin/bash

# Help script for Backthynk Development Makefile
source "$(dirname "$0")/../common/load-config.sh"

echo -e "${BOLD}${CYAN}Backthynk Development Makefile${NC}"
echo -e "${CYAN}==============================${NC}"
echo ""
echo -e "${BOLD}Available targets:${NC}"
echo ""
echo -e "  ${YELLOW}Build & Run:${NC}"
echo -e "    ${GREEN}build${NC}                    Build the application binary"
echo -e "    ${GREEN}build-prod${NC}               Build optimized production binary with compressed assets"
echo -e "    ${GREEN}run${NC}                      Run the server (builds if necessary)"
echo -e "    ${GREEN}serve-dev${NC}                Run the server in development mode"
echo -e "    ${GREEN}serve-prod${NC}               Run the server in production mode"
echo -e "    ${GREEN}clean${NC}                    Clean build artifacts"
echo ""
echo -e "  ${YELLOW}Testing:${NC}"
echo -e "    ${GREEN}test${NC}                     Run all backend unit tests"
echo -e "    ${GREEN}test-verbose${NC}             Run all backend unit tests with verbose output"
echo ""
echo -e "  ${YELLOW}CSS Optimization:${NC}"
echo -e "    ${GREEN}extract-css${NC}              Extract minimal CSS from Tailwind and Font Awesome"
echo -e "    ${GREEN}deps-css${NC}                 Download CSS extraction dependencies"
echo ""
echo -e "  ${YELLOW}Development Scripts:${NC}"
echo -e "    ${GREEN}dev-generate-posts${NC}       Generate random posts for testing"
echo -e "    ${GREEN}dev-list-categories${NC}      List all available categories"
echo ""